#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

my $prefix = '/App/reposdb/';
Perinci::CmdLine::Any->new(
    url => $prefix,
    subcommands => {
        ls                => {url => "${prefix}list_repos"},
        touch             => {url => "${prefix}touch_repo"},
        tag               => {url => "${prefix}add_repo_tag"},
        'remove-tag'      => {url => "${prefix}remove_repo_tag"},
        'remove-all-tags' => {url => "${prefix}remove_all_repo_tags"},
        get               => {url => "${prefix}get_repo_metadata"},
    },
    log => 1,
)->run;

1;
# ABSTRACT:
# PODNAME:

=head1 DESCRIPTION
